language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - "10"
notifications:
  email: false
stages:
  - test
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: test
      name: eslint
      script: npx eslint .
    - stage: test
      name: commitlint
      before_script:
        - npm i -g @commitlint/travis-cli
      script: commitlint-travis
    - stage: test
      node_js:
        - "10"
        - "8"
      script: npm t
    - stage: deploy
      script: npx semantic-release
